# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'

  # Maintain dependencies for main packages
  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'

  # Maintain dependencies for frontend apps
  - package-ecosystem: 'npm'
    directory: '/apps/frontend'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'

  # Maintain dependencies for backend apps
  - package-ecosystem: 'npm'
    directory: '/apps/backend'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'

  # Maintain dependencies for database packages
  - package-ecosystem: 'npm'
    directory: '/packages/database'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'

  # Maintain dependencies for eslint-config-custom packages
  - package-ecosystem: 'npm'
    directory: '/packages/eslint-config-custom'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
